### PR TITLE
Fix error when statistics are saving

### LINKED ISSUE #592: Ошибка доступа к main.plua при создании файла статистики
Когда файл main.plua ещё не создан и пытается сгенерироваться статистика, вываливается эксепшн.

### PR DESCRIPTION
**Pull request by dimabeel**
Fixes #592.

### CODE REVIEW

File: src/FileSavers/SVGStatisticsSaver.cs [hunk 1]
```diff
@@ -193,12 +197,12 @@ private static void WriteFile(string text, string folderPath)
...
-        static string countOfUnitsFileName = "units_total.svg";
-        static string countOfEquipmentModulesFileName = "agregates_total.svg";
-        static string countOfDevicesFileName = "devices_total.svg";
-        static string ioModulesInPercentage = "io_link_usage.svg";
+        const string linesOfCodeMainProgramFileName = "lines_total.svg";
+        const string countOfTagsFileName = "tags_total.svg";
+        const string countOfUnitsFileName = "units_total.svg";
+        const string countOfEquipmentModulesFileName = "agregates_total.svg";
+        const string countOfDevicesFileName = "devices_total.svg";
+        const string ioModulesInPercentage = "io_link_usage.svg";
```
Comment (idzm) [inline src/FileSavers/SVGStatisticsSaver.cs:205]:
```suggestion
        const string LinesOfCodeMainProgramFileName = "lines_total.svg";
        const string CountOfTagsFileName = "tags_total.svg";
        const string СountOfUnitsFileName = "units_total.svg";
        const string СountOfEquipmentModulesFileName = "agregates_total.svg";
        const string СountOfDevicesFileName = "devices_total.svg";
        const string IOModulesInPercentage = "io_link_usage.svg";
```

**Review by idzm — CHANGES_REQUESTED** [review]

**Review by idzm — APPROVED** [review]
