### PR TITLE
Fix disable edit mode on close editor

### LINKED ISSUE #1245: Снимать флаг редактирования объектов
При закрытии поля редактирования описания технологических объектов, то нужно автоматически снимать флаг редактирования объектов.

### PR DESCRIPTION
**Pull request by KirillGutyrchik**
Fixes #1245.

### CODE REVIEW

File: src/Editor/NewEditorControl.cs [hunk 1]
```diff
@@ -445,11 +445,11 @@ private IntPtr DlgWndHookCallbackFunction(int code, IntPtr wParam, IntPtr lParam
             PI.CWPSTRUCT msg =
                 (PI.CWPSTRUCT)System.Runtime.InteropServices.Marshal.PtrToStructure(lParam, typeof(PI.CWPSTRUCT));
 
-            // 0xC0C7 - зарегистрированное сообщение AFX_WM_ON_PRESS_CLOSE_BUTTON, вызываемое при закрытии дочернего окна в EPLAN.
+            // AFX_WM_ON_PRESS_CLOSE_BUTTON - зарегестрированное сообщение, вызываемое при закрытии дочернего окна в EPLAN.
```
Comment (idzm) [inline src/Editor/NewEditorControl.cs:448]:
```suggestion
            // AFX_WM_ON_PRESS_CLOSE_BUTTON - зарегистрированное сообщение, вызываемое при закрытии дочернего окна в EPLAN.
```

**Review by idzm — CHANGES_REQUESTED** [review]

**Review by idzm — APPROVED** [review]
